.PHONY: clean All

All:
	@echo "----------Building project:[ c1020a23Lab4 - Debug ]----------"
	@cd "makeBinaryLab4" && "$(MAKE)" -f  "c1020a23Lab4.mk"
clean:
	@echo "----------Cleaning project:[ c1020a23Lab4 - Debug ]----------"
	@cd "makeBinaryLab4" && "$(MAKE)" -f  "c1020a23Lab4.mk" clean
