.PHONY: clean All

All:
	@echo "----------Building project:[ c1020a23Lab3 - Debug ]----------"
	@cd "c1020a23Lab3" && "$(MAKE)" -f  "c1020a23Lab3.mk"
clean:
	@echo "----------Cleaning project:[ c1020a23Lab3 - Debug ]----------"
	@cd "c1020a23Lab3" && "$(MAKE)" -f  "c1020a23Lab3.mk" clean
